#!/bin/bash

echo "🚀 Deploying RCA Platform to Railway"
echo "====================================="
echo ""

echo "📋 Railway Deployment Steps:"
echo ""
echo "1. Go to https://railway.app/"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project'"
echo "4. Choose 'Deploy from GitHub repo'"
echo "5. Select: ananya15082002/rca-platform"
echo "6. Railway will auto-detect Python project"
echo ""

echo "🗄️  Add PostgreSQL Database:"
echo "1. In your Railway project"
echo "2. Click 'New' → 'Database' → 'PostgreSQL'"
echo "3. Railway will auto-set DATABASE_URL"
echo ""

echo "🔧 Set Environment Variables:"
echo "In Railway dashboard → Variables:"
echo ""
echo "GOOGLE_CHAT_WEBHOOK_URL=https://chat.googleapis.com/v1/spaces/AAQAJSJGzQo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=lrJ-5USNWwEZcG7p0e9X6uQTGYeLn60yY7SkgpTXUhQ"
echo "METRIC_URL=http://observability-prod.fxtrt.io:3130/api/metrics/api/v1/query_range"
echo "TRACE_BASE_URL=https://cubeapm-newrelic-prod.fxtrt.io/api/traces/api/v1/search"
echo "LOGS_API_URL=http://observability-prod.fxtrt.io:3130/api/logs/select/logsql/query"
echo "ENVIRONMENT=production"
echo ""

echo "🎯 What You'll Get:"
echo "   ✅ Backend API on Railway"
echo "   ✅ PostgreSQL database"
echo "   ✅ Automatic deployments"
echo "   ✅ SSL certificates"
echo "   ✅ Custom domains"
echo "   ✅ Built-in monitoring"
echo ""

echo "🚀 Ready to deploy! Follow the steps above."
echo ""
echo "💡 Pro tip: Railway provides free tier with:"
echo "   - 500 hours/month"
echo "   - 1GB storage"
echo "   - 512MB RAM"
echo "   - PostgreSQL included" 